// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback:                       1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    update_attributes
    (
        init => init
        upgrade => upgrade
        issue_fungible_token_mapper => issue_fungible_token_mapper
        issue_non_fungible => issue_non_fungible
        issue_fungible => issue_fungible
        set_roles => set_roles
        create_nft => create_nft
        update_attributes => update_attributes
        send_nft => send_nft
        nft_token_id => nft_token_id
        test_token_mapper => test_token_mapper
    )
}

multiversx_sc_wasm_adapter::async_callback! { update_attributes }
